# Game settings and constants

PLAYER_DEFAULT_NAME = "Hero"
NPC_DEFAULT_NAME = "Goblin"

PLAYER_DEFAULT_HEALTH = 100
NPC_DEFAULT_HEALTH = 50
PLAYER_DEFAULT_ATTACK = 15
PLAYER_DEFAULT_DEFENSE = 5
NPC_DEFAULT_ATTACK = 10
NPC_DEFAULT_DEFENSE = 3
